### ISSUE TITLE
资源有一张背景图片丢失了，编号1370

### ISSUE THREAD

**Issue by DreamGallery** [wds-sirius/Adv-Resource#1]
今天上传水团联动翻译的时候尝试播放看了下，第八话会报错，然后看了控制台信息，发现是有一张背景少了
**https://raw.githubusercontent.com/wds-sirius/Adv-Resource/main/background/1370.png**
应该是需要再添加一下了

**Comment by Cpk0521** [comment]
感謝回報
剛剛看了一下原因
發現是因為1370的assetsbundle中的圖片名字跟編號不符 
所以找不到檔案匯出出來 
![image](https://github.com/user-attachments/assets/6b33d27f-e0f5-4bc9-87f9-a6eba4662fe7)
現已手動上傳了

**Comment by DreamGallery** [comment]
辛苦了
